apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfsexterno
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    # FIXME: use the right IP
    server: dns.infra.caasp.local
    path: "/home"
